name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch: 

# Credenciais globais para a CONTA B (Criação de recursos)
env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "sa-east-1"

jobs:
  plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    container: hashicorp/terraform:1.14.8
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Init
        run: |
          terraform init -input=false -reconfigure \
            -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID_STATE }}" \
            -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY_STATE }}" \
            -backend-config="region=sa-east-1" \
            -backend-config="bucket=terraform-starter-bucket-b8uzs" \
            -backend-config="key=terraform.tfstate"
      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  apply:
    name: 'Terraform Apply'
    needs: plan
    runs-on: ubuntu-latest
    environment: production # Exige aprovação manual se configurado no repositório [1]
    container: hashicorp/terraform:1.14.8
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: tfplan
      - name: Terraform Apply
        run: |
          # Inicialização necessária para o backend antes do apply [1]
          terraform init -input=false -reconfigure \
            -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID_STATE }}" \
            -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY_STATE }}" \
            -backend-config="region=sa-east-1" \
            -backend-config="bucket=terraform-starter-bucket-b8uzs" \
            -backend-config="key=terraform.tfstate"
          terraform apply -input=false tfplan [1]

  destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment: destroy-prod # Garante a pausa manual [1]
    container: hashicorp/terraform:1.14.8
    env:
      # Injeta as chaves para evitar erro de "empty token" [1]
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Destroy
        run: |
          # Inicialização do backend para o destroy [1]
          terraform init -input=false -reconfigure \
            -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID_STATE }}" \
            -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY_STATE }}" \
            -backend-config="region=sa-east-1" \
            -backend-config="bucket=terraform-starter-bucket-b8uzs" \
            -backend-config="key=terraform.tfstate"
          terraform destroy -auto-approve [1]